@startuml
'https://plantuml.com/class-diagram


class DICGrid {
  U_tija
}

class DICStateFields{

}

DICStateFields --> DICGrid

class DICCrack {
   index_range
}

DICCrackList --> DICStateFields

DICCrackList *--> DICCrack

class DICAlign{
}

class DICCOR{
}

@enduml