@startuml
'https://plantuml.com/class-diagram

interface IDICGrid {
  X_IJa
  U_TIJa
  F_T
  time_T
  w_T
  t
}

class DICGrid {
}

DICGrid --|> IDICGrid

class DICGridTri {
}

DICGridTri --|> IDICGrid

class DICStateFields{
  U_TMNa
  omega_TMN
}

DICStateFields --> IDICGrid

class DICCrack {
   index_range
}

DICCrackList --> DICStateFields

DICCrackList *--> DICCrack

DICCrack --> IDICGrid

DICCrack --> DICStressProfile

DICStressProfile --> IDICGrid

class DICAlign{
}

class DICCOR{
}

@enduml