@startuml
'https://plantuml.com/class-diagram


class DICGrid {
  U_TIJa
  t
  T0
  T1
}

class DICStateFields{
  U_TMNa
  omega_TMN
}

DICStateFields --> DICGrid

class DICCrack {
   index_range
}

DICCrackList --> DICStateFields

DICCrackList *--> DICCrack

DICCrack --> DICGrid

DICCrack --> DICStressProfile

DICStressProfile --> DICGrid

class DICAlign{
}

class DICCOR{
}

@enduml